### PR TITLE
added support for rp235x, fix for dht11, porting to embedded-hal 1.0.0

### PR DESCRIPTION
**Pull request by vescoc**
Misc:
- porting to embedded-hal 1.0.0
- added support to Raspberry PI Pico2 (rp235x). You can select the MCU by cargo build --feature rp2040 or cargo build --feature rp235x with target MCU thumbv6m-none-eabi (pico), thumbv8m.main-none-eabihf (pico2 arm mode) and riscv32imac-unknown-none-elf (pico2 riscv mode)
- support (fix) and testing for DHT11 on pico and pico2 arm
- test for DHT22 on pico and pico2 arm

note: I think we need rust 1.82 for supporing #[unsafe(link_section)]

### CODE REVIEW

**Review by jnthbdn — APPROVED** [review]

**Comment by jnthbdn** [comment]
Hi !

Nice PR thank you !
Indeed this code is a bit old and I was very young in Rust dev ^^.

Can you update the README, to explain the "build features" ?

**Comment by vescoc** [comment]
> Hi !
> 
> Nice PR thank you ! Indeed this code is a bit old and I was very young in Rust dev ^^.
> 
> Can you update the README, to explain the "build features" ?
Thanks for the positive review!

My english is very bad, please check if is ok.

**Comment by vescoc** [comment]
Any news?

**Comment by jnthbdn** [comment]
Sorry for the delay ^^

**Comment by jnthbdn** [comment]
Version 0.6.1 is published on crates.io (due to an old error version 0.6.0 already exists on crates.io....but yanked)

**Pull request merged**
